### PR TITLE
Dox.config.body_format added with possible values :json (default) and…

### PR DESCRIPTION
**Pull request by mpakus**
Good day folks!

First of all, thank you for Dox, I'm moving from rspec_api_document and I like how this gem's separates API description and tests.

but I had some issue with Dox when you use it not with JSONAPI specification it fall on parsing request of the body.

So, I've decided to create a small patch which you can look at now.
I added `Dox.config.body_format` this option it able to be one of the format `:json` or `:query`

Option is backward compatible and `back_format` equal to `:json` by default but when you don't want to send param as json in the body you should turn `back_format` it to the `:query` value.

That's it, very simple and it works for me, so maybe will be helpful to someone else.

Thanks.

### CODE REVIEW

**Comment by mpakus** [comment]
ping ping... anyone is alive?

**Comment by melcha** [comment]
Hello @mpakus,

thank you very much for your contribution! 

I'm very busy at the moment, but I will take a look at the code as soon as I can.

**Comment by melcha** [comment]
Hey @mpakus,

thanks again and sorry for the late response. 

Dox currently works only with json payloads (for requests and responses), which is not ideal and it would be great to add a support for other formats, such as plain text, xml.. 

I checked out your PR and tried to run it with the [dox-demo app](https://github.com/infinum/dox-demo), but it crashes in `ExamplePrinter` line #55, because it doesn’t get a json and it calls `JSON.pretty_generate(json_string)`. 

Otherwise, your solution to this problem is simple and fine. But it would be even better if we wouldn’t have to set the format type on the global level in the config, but determine it on request/response level. We should use `Content-Type` header for detecting the body format, for both request and response independently, and print the bodies according to the format.

As for the actual printing in the `ExamplePrinter`, I think it’s best for now to remove pretty_json method from there and add two new methods to the `Example` entity class, `formatted_request_body` and `formatted_response_body` which would be responsible for formatting the body and the printer would simply call these methods. 

Are you interested in implementing this feature as described? If not, I could implement it sometime next week.

**Comment by mpakus** [comment]
@melcha yeah, sounds good, let me check what I can do with that new idea at next week 👍🏼

**Comment by melcha** [comment]
Hey @mpakus, did you get a chance to start working on this?

**Comment by mpakus** [comment]
yep, I tried but haven't so much time to finish properly check it. Going to try it later.

**Comment by melcha** [comment]
This is fixed in the new 1.1.0 version: https://github.com/infinum/dox/blob/master/CHANGES.md#version-110.

**Pull request closed without merging**
